# À propos des auteurs {#auteurs .unnumbered}

[**Samuel Foucher**](https://www.usherbrooke.ca/recherche/fr/specialistes/details/samuel.foucher) est professeur au [Département de géomatique appliquée](https://www.usherbrooke.ca/geomatique/) de l'[Université de Sherbrooke](https://www.usherbrooke.ca/). Il y enseigne aux [programmes de 1^er^ et 2^e^ cycles de géomatique](https://www.usherbrooke.ca/geomatique/etudes/programmes) les cours *Traitement numérique des images de télédétection*, *Base de données géospatiales* et *Apprentissage profond appliqué à l'observation de la Terre*. Ses intérêts de recherche portent sur le traitement d'images et l'application de l'IA aux données géospatiales.

[**Philippe Apparicio**](https://www.usherbrooke.ca/recherche/fr/specialistes/details/philippe.apparicio) est professeur titulaire au [Département de géomatique appliquée](https://www.usherbrooke.ca/geomatique/) de l'[Université de Sherbrooke](https://www.usherbrooke.ca/). Il y enseigne aux [programmes de 1^er^ et 2^e^ cycles de géomatique](https://www.usherbrooke.ca/geomatique/etudes/programmes) les cours *Transport et mobilité durable*, *Modélisation et analyse spatiale* et *Géomatique appliquée à la gestion urbaine*. Durant les dernières années, il a offert plusieurs formations aux Écoles d'été du Centre interuniversitaire québécois de statistiques sociales ([CIQSS](https://www.ciqss.org/)). Géographe de formation, ses intérêts de recherche incluent la justice et l'équité environnementale, la mobilité durable, les pollutions atmosphérique et sonore, et le vélo en ville. Il a publié une centaine d'articles scientifiques dans différents domaines des études urbaines et de la géographie mobilisant la géomatique et l'analyse spatiale.

[**Mickaël Germain**](https://www.usherbrooke.ca/geomatique/departement/personnel/personnel-enseignant/mickael-germain) est professeur agrégé au [Département de géomatique appliquée](https://www.usherbrooke.ca/geomatique/) de l'[Université de Sherbrooke](https://www.usherbrooke.ca/). Ses expertises comprennent les systèmes d’information géographique (SIG) et leur utilisation sur Internet (SIG web), les systèmes décisionnels, les bases de données à référence spatiale et le forage de données massives. Il s'intéresse également à la cartographie web, à la mobilité, à l’Internet des objets (IoT), à l’apprentissage machine et à la fusion des données multisources pour l’aide à la décision. Ses systèmes sont utilisés dans divers domaines de la géomatique tels que les ressources naturelles, la géologie, les transports et les écosystèmes. De plus, il se passionne pour le traitement, la gestion et l'analyse des données de télédétection pour extraire des paramètres descriptifs facilitant l'identification, la segmentation ou la classification de l'information.

[**Yacine Bouroubi**](https://www.usherbrooke.ca/geomatique/departement/personnel/personnel-enseignant/yacine-bouroubi) est professeur agrégé au [Département de géomatique appliquée](https://www.usherbrooke.ca/geomatique/) de l'[Université de Sherbrooke](https://www.usherbrooke.ca/). Il possède plus de vingt ans d'expérience dans le domaine du traitement des images numériques appliqué à diverses thématiques des sciences6. Ses travaux de recherche se concentrent principalement sur l'utilisation de techniques de traitement d'images pour résoudre des problèmes géographiques. En tant que professeur, il partage son expertise avec les étudiants et contribue à l'avancement des connaissances dans son domaine. Bien que les détails spécifiques de sa carrière ne soient pas fournis, son expérience étendue et son poste actuel témoignent de sa contribution significative à la géographie et au traitement d'images numériques.

[**Étienne Clabaut**](https://www.linkedin.com/in/%C3%A9tienne-clabaut-793a4176/?originalSubdomain=ca) est professeur associé au [Département de géomatique appliquée](https://www.usherbrooke.ca/geomatique/) de l'[Université de Sherbrooke](https://www.usherbrooke.ca/). Étienne détient un doctorat en télédétection de l'Université de Sherbrooke. Il se spécialise dans l'utilisation de l'apprentissage automatique pour l'exploitation de l'imagerie satellite.s